version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12

    steps:
      - run: ls
      - checkout
      - run: ls

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: echo //npm.pkg.github.com/:_authToken=${GITHUB_TOKEN} > ~/.npmrc
      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn build
